steps:
# Copy the website content to a GS bucket
- name: 'gcr.io/cloud-builders/gsutil'
  id: Sync the website content
  args: ["-m", "rsync", "-r", "-c", "-d", ".", 'gs://www.devpatel.cloud']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: Invalidate the content CDN
  args: ['gcloud', 'compute', 'url-maps', 'invalidate-cdn-cache', 'personal-website-lb', '--path', '/*', '--project', 'person-388105']
