steps:
# Copy the website content to a GS bucket
- name: 'gcr.io/cloud-builders/gsutil'
  id: Sync the website content
  args: ["-m", "rsync", "-r", "-c", "-d", ".", 'gs://www.devpatel.cloud']
 - name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'backend-services', 'update', 'personal-website-lb', '--global', '--cache-key-include-host', 'include_host', '--cache-key-include-host', 'www.devpate.cloud', 'invalidate-cdn-cache']
