steps:
# Copy the website content to a GS bucket
- name: 'gcr.io/cloud-builders/gsutil'
  id: Sync the website content
  args: ["-m", "rsync", "-r", "-c", "-d", ".", 'gs://www.devpatel.cloud']
- name: 'gcr.io/cloud-builders/gcloud'
  id: Invalidate CDN Cache
  args: ['compute', 'url-maps', 'invalidate-cdn-cache', 'personal-website-lb', '--path', '/*', '--async']

